services:

  hpstatus:

    container_name: hpstatus

    build:
      context: .

    restart: unless-stopped


    ports:
      - "5122:80"


    environment:

      ASPNETCORE_ENVIRONMENT: Production

      ASPNETCORE_URLS: http://+:80

      DATA_PATH: /app/Data


    volumes:

      - ./Data:/app/Data