services:
  hpstatus:
    build:
      context: .

    container_name: hpstatus


    restart: unless-stopped


    ports:
      - "5122:80"


    environment:

      ASPNETCORE_ENVIRONMENT: Production

      ASPNETCORE_URLS: http://+:80

      DATA_PATH: /app/Data
      HYPIXEL_API_KEY: ${HYPIXEL_API_KEY}
      ADMIN_KEY: ${ADMIN_KEY}

    volumes:

      - ./Data:/app/Data